/* Autogenerated file. Do not edit manually. */

package {{.Package}};

import (
	"errors"
	"math/big"

	"github.com/ethereum/go-ethereum/concrete/codegen/datamod"
	"github.com/ethereum/go-ethereum/concrete/lib"
)

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ = errors.New
	_ = big.NewInt
)

type {{.StructName}} struct {
    datamod.StorageStruct
}

func New{{.StructName}}(slot lib.StorageSlot) *{{.StructName}} {
    sizes := {{.Sizes}}
    return &{{.StructName}}{*datamod.NewStorageStruct(slot, sizes)}
}

func (item *{{$.StructName}}) Get() ({{range .Schema.Values}}
    {{.Type.GoType}}, {{end}}
) {
    return {{range .Schema.Values}}datamod.{{.Type.DecodeFunc}}({{.Type.Size}}, item.GetField({{.Index}})){{if eq .Index (sub (len $.Schema.Values) 1)}}{{else}}, {{end}}{{end}}
}

func (item *{{$.StructName}}) Set({{range .Schema.Values}}
    {{.Name}} {{.Type.GoType}}, {{end}}
) {{"{"}}{{range .Schema.Values}}
    item.SetField({{.Index}}, datamod.{{.Type.EncodeFunc}}({{.Type.Size}}, {{.Name}})){{end}}
}
{{range .Schema.Values}}
func (item *{{$.StructName}}) Get{{.Title}}() {{.Type.GoType}} {
    data := item.GetField({{.Index}})
    return datamod.{{.Type.DecodeFunc}}({{.Type.Size}}, data)
}

func (item *{{$.StructName}}) Set{{.Title}}(value {{.Type.GoType}}) {
    data := datamod.{{.Type.EncodeFunc}}({{.Type.Size}}, value)
    item.SetField({{.Index}}, data)
}
{{end}}