/* Autogenerated file. Do not edit manually. */

package {{.Package}}

import (
	"math/big"

	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/concrete/codegen/datamod/codec"
	"github.com/ethereum/go-ethereum/concrete/crypto"
	"github.com/ethereum/go-ethereum/concrete/lib"
)

// Reference imports to suppress errors if they are not otherwise used.
var (
	_ = big.NewInt
	_ = common.Big1
	_ = codec.EncodeAddress
)

var (
	{{.TableStructName}}DefaultKey = crypto.Keccak256([]byte("datamod.v1.{{.TableStructName}}"))
)

type {{.RowStructName}} struct {
	lib.StorageStruct
}

func New{{.RowStructName}}(store lib.StoreValue) *{{.RowStructName}} {
	sizes := {{.SizesStr}}
	return &{{.RowStructName}}{*lib.NewStorageStruct(store, sizes)}
}

func (v *{{$.RowStructName}}) Get() (
{{- range .Schema.Values }}
	{{.Type.GoType}},
{{- end }}
) {
	return {{ range .Schema.Values -}}
		codec.{{.Type.DecodeFunc}}(
			{{- .Type.Size }}, v.GetField({{.Index}}))
			{{- if eq .Index (sub (len $.Schema.Values) 1) }}{{else}}, {{end}}
	{{- end }}
}

func (v *{{$.RowStructName}}) Set(
{{- range .Schema.Values }}
	{{.Name}} {{.Type.GoType}},
{{- end }}
) {
{{- range .Schema.Values }}
	v.SetField({{.Index}}, codec.{{.Type.EncodeFunc}}({{.Type.Size}}, {{.Name}}))
{{- end }}
}
{{range .Schema.Values}}
func (v *{{$.RowStructName}}) Get{{.Title}}() {{.Type.GoType}} {
	data := v.GetField({{.Index}})
	return codec.{{.Type.DecodeFunc}}({{.Type.Size}}, data)
}

func (v *{{$.RowStructName}}) Set{{.Title}}(value {{.Type.GoType}}) {
	data := codec.{{.Type.EncodeFunc}}({{.Type.Size}}, value)
	v.SetField({{.Index}}, data)
}
{{end}}
{{- if .Schema.Keys }}
type {{.TableStructName}} struct {
	store lib.StoreValue
}

func New{{.TableStructName}}(ds lib.Datastore) *{{.TableStructName}} {
	return &{{.TableStructName}}{ds.Value({{.TableStructName}}DefaultKey)}
}

func New{{.TableStructName}}WithKey(ds lib.Datastore, key []byte) *{{.TableStructName}} {
	return &{{.TableStructName}}{ds.Value(key)}
}

func (m *{{.TableStructName}}) Get(
{{- range .Schema.Keys }}
	{{.Name}} {{.Type.GoType}},
{{- end }}
) *{{.RowStructName}} {
	store := m.store.Mapping().NestedValue(
		{{- range .Schema.Keys }}
		codec.{{.Type.EncodeFunc}}({{.Type.Size}}, {{.Name}}),
		{{- end }}
	)
	return New{{.RowStructName}}(store)
}
{{- else }}
type {{.TableStructName}} = {{.RowStructName}}

func New{{.TableStructName}}(ds lib.Datastore) *{{.TableStructName}} {
	store := ds.Value({{.TableStructName}}DefaultKey)
	return New{{.RowStructName}}(store)
}

func New{{.TableStructName}}WithKey(ds lib.Datastore, key []byte) *{{.TableStructName}} {
	store := ds.Value(key)
	return New{{.RowStructName}}(store)
}
{{- end }}
